on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Meteor'
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.12'

      - name: 'Install dependencies'
        run: meteor npm run install:${{ inputs.name }}

      - name: 'Link meteor-vite package'
        run: meteor npm run link:${{ inputs.name }}

      - name: 'Build for production'
        run: meteor npm run build:${{ inputs.name }}