name: Example Apps

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  vue:
    name: Vue
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: vue

  svelte:
    name: Svelte
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: svelte

  react:
    name: React
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: react
