name: 'Build Example Apps'

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  build-vue-example:
    name: 'Build Vue App'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Meteor'
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.10.0'
      - name: 'Install dependencies'
        run: cd examples/vue && meteor npm install
      - name: 'Build for production'
        run: cd examples/vue && meteor npm run build


