name: 'Build Example Apps'

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  vue:
    name: 'Vue Example'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: 'vue'

  svelte:
    name: 'Svelte Example'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: 'svelte'